const STATES = Object.freeze({
  IDLE: 'idle', LISTENING: 'listening', SPEECH_DETECTED: 'speech-detected',
  TRANSCRIBING: 'transcribing', THINKING: 'thinking', RESPONDING: 'responding',
  INTERRUPTED: 'interrupted', ERROR: 'error',
});
const TRANSITIONS = {
  [STATES.IDLE]: [STATES.LISTENING, STATES.ERROR],
  [STATES.LISTENING]: [STATES.SPEECH_DETECTED, STATES.IDLE, STATES.ERROR],
  [STATES.SPEECH_DETECTED]: [STATES.TRANSCRIBING, STATES.INTERRUPTED, STATES.ERROR],
  [STATES.TRANSCRIBING]: [STATES.THINKING, STATES.IDLE, STATES.ERROR],
  [STATES.THINKING]: [STATES.RESPONDING, STATES.INTERRUPTED, STATES.ERROR],
  [STATES.RESPONDING]: [STATES.LISTENING, STATES.INTERRUPTED, STATES.IDLE, STATES.ERROR],
  [STATES.INTERRUPTED]: [STATES.LISTENING, STATES.IDLE, STATES.ERROR],
  [STATES.ERROR]: [STATES.IDLE, STATES.LISTENING],
};
function canTransition(from, to) { return Boolean(TRANSITIONS[from]?.includes(to)); }
module.exports = { STATES, TRANSITIONS, canTransition };
